apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: demo-app-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: github-push-main
      interceptors:
        - ref:
            name: github
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: secretRef
              value:
                secretName: github-webhook-secret
                secretKey: secretToken
            - name: eventTypes
              value:
                - push
        - ref:
            name: cel
            kind: ClusterInterceptor
            apiVersion: triggers.tekton.dev
          params:
            - name: filter
              value: "body.ref == 'refs/heads/main'"
      bindings:
        - ref: demo-app-binding
      template:
        ref: demo-app-template
