apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: demo-app-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: revision
      value: $(body.after)
    - name: repo-url
      value: $(body.repository.clone_url)
