apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: demo-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Germain-L/tekton-demo-app.git
  secretRef:
    name: demo-app-git
  ref:
    branch: main
